'\" t
.\"     Title: spin
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 2023-07-25
.\"    Manual: tailspin
.\"    Source: tailspin 1.2.0
.\"  Language: English
.\"
.TH "SPIN" "1" "2023-07-25" "tailspin 1.2.0" "tailspin"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
spin \- A log file highlighter
.SH "SYNOPSIS"
.sp
\fBspin\fP [\fIOPTION\fP]... [\fIFILE\fP]...
.SH "DESCRIPTION"
.sp
spin is a command line tool that highlights log files.
.SH "OPTIONS"
.sp
\fB\-f, \-\-follow\fP
.RS 4
Follow (tail) the contents of the file.
.RE
.sp
\fB\-p, \-\-print\fP
.RS 4
Print the output to stdout instead of viewing the contents in the pager \fIless\fP.
.RE
.sp
\fB\-c, \-\-config\-path\fP \fICONFIG_PATH\fP
.RS 4
Specify the path to a custom configuration file.
.RE
.sp
\fB\-t, \-\-tail\-command\fP \fICOMMAND\fP
.RS 4
Tail the output of the provided command.
Useful for when you have a command which continuously prints to stdout.
The command traps the interrupt signal to allow for cancelling and resuming tailing while inside \fIless\fP.
.RE
.sp
\fB\-\-generate\-config\fP
.RS 4
Generate a new configuration file.
Uses XDG_CONFIG_HOME as the location if set.
Otherwise, uses ~/.config/tailspin/config.toml as the default path.
Will not overwrite current config file if one is already present.
.RE
.sp
\fB\-\-show\-default\-config\fP
.RS 4
Print the default configuration.
.RE
.SH "SEE ALSO"
.sp
\fBless\fP(1), \fBtail\fP(1)
.SH "ABOUT"
.sp
Ben Sadeh (github.com/bensadeh/tailspin)
.sp
Released under the MIT License