.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH spin 1  "spin 1.2.0" 
.SH NAME
spin \- A log file highlighter
.SH SYNOPSIS
\fBspin\fR [\fB\-f\fR|\fB\-\-follow\fR] [\fB\-p\fR|\fB\-\-print\fR] [\fB\-c\fR|\fB\-\-config\-path\fR] [\fB\-t\fR|\fB\-\-tail\-command\fR] [\fB\-\-create\-default\-config\fR] [\fB\-\-show\-default\-config\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIFILE\fR] 
.SH DESCRIPTION
A log file highlighter
.SH OPTIONS
.TP
\fB\-f\fR, \fB\-\-follow\fR
Follow (tail) the contents of the file
.TP
\fB\-p\fR, \fB\-\-print\fR
Print the output to stdout
.TP
\fB\-c\fR, \fB\-\-config\-path\fR=\fICONFIG_PATH\fR
Path to a custom configuration file
.TP
\fB\-t\fR, \fB\-\-tail\-command\fR=\fITAIL_COMMAND\fR
Tails the output of the provided command
.TP
\fB\-\-create\-default\-config\fR
Generate a new configuration file
.TP
\fB\-\-show\-default\-config\fR
Print the default configuration
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
[\fIFILE\fR]
Filepath
.SH VERSION
v1.2.0
.SH AUTHORS
Ben Sadeh
