'\" t
.\"     Title: tspin
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2025-05-25
.\"    Manual: tailspin
.\"    Source: tailspin 5.4.3
.\"  Language: English
.\"
.TH "TSPIN" "1" "2025-05-25" "tailspin 5.4.3" "tailspin"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
tspin \- A log file highlighter
.SH "SYNOPSIS"
.sp
\fBtspin\fP [\fIOPTION\fP]... [\fIFILE\fP]...
.SH "DESCRIPTION"
.sp
tailspin is a command line tool that highlights log files.
.SH "OPTIONS"
.sp
\fI\-f, \-\-follow\fP
.RS 4
Follow (tail) the contents of the file.
Always true when using the \fI\-\-follow\-command\fP flag.
.RE
.sp
\fI\-p, \-\-print\fP
.RS 4
Print the output to stdout instead of viewing the contents in the pager \fIless\fP.
Always true if using stdin.
.RE
.sp
\fI\-\-config\-path\fP \fBCONFIG_PATH\fP
.RS 4
Specify the path to a custom configuration file.
Defaults to \fBXDG_CONFIG_HOME/tailspin/theme.toml\fP or \fB~/.config/tailspin/theme.toml\fP if not set.
.RE
.sp
\fI\-e, \-\-exec\fP \fBCOMMAND\fP
.RS 4
Run command and view the output in a pager.
The command traps the interrupt signal to allow for cancelling and resuming follow mode while inside \fIless\fP.
.sp
.B Example:
.br
.sp
.if n .RS 4
.nf
.fam C
tspin \-\-listen\-command \*(Aqkubectl logs \-f pod_name\*(Aq
.fam
.fi
.if n .RE
.RE
.sp
\fI\-\-highlight\fP \fBCOLOR1\fP:\fIword1,word2,...\fP \fBCOLOR2\fP:\fIword3,word4,...\fP
.RS 4
Highlight the provided comma\-separated words in the specified color.
Possible colors are red, green, yellow, blue, magenta, and cyan.
.sp
.B Example:
.br
.sp
.if n .RS 4
.nf
.fam C
tspin logfile.txt \-\-highlight red:error,fail \-\-highlight green:success,ok
.fam
.fi
.if n .RE
.RE
.sp
\fI\-\-enable=[HIGHLIGHT_GROUP]\fP
.RS 4
Disable all highlighting groups except the ones specified.
Comma separated list of groups.
Cannot be used with \fB\-\-disable=[HIGHLIGHT_GROUP]\fP.
.RE
.sp
\fI\-\-disable=[HIGHLIGHT_GROUP]\fP
.RS 4
Disable the specified highlighting groups.
Comma separated list of groups.
Cannot be used with \fB\-\-enable=[HIGHLIGHT_GROUP]\fP.
.RE
.sp
\fI\-\-disable\-builtin\-keywords\fP
.RS 4
Disables the highlighting of all builtin keyword groups (booleans, severity and REST).
.RE
.SH "ENVIRONMENT VARIABLES"
.sp
\fBTAILSPIN_PAGER\fP
.RS 4
Set the \fITAILSPIN_PAGER\fP environment variable to override the default pager.
The command must include the string \fI[FILE]\fP which will be replaced with the file path internally.
For example, \fI"ov \-f [FILE]"\fP.
.RE
.SH "SEE ALSO"
.sp
\fBless\fP(1), \fBtail\fP(1)
.SH "ABOUT"
.sp
Ben Sadeh (github.com/bensadeh/tailspin)
.sp
Released under the MIT License