[pointer]
number = { fg = "green" }
letter = { fg = "blue" }
x = { fg = "red" }

[[regexps]]
regex = 'Started (.*)\.'
style = { fg = "red" }

[[regexps]]
regex = 'Stopped .*'
style = { fg = "magenta" }
