= spin(1)
:doctype: manpage
:manmanual: tailspin
:man source: tailspin {release-version}
:revdate: {docdate}

ifdef::env-github[]
:toc:
:toc-title:
:toc-placement!:
:numbered:
endif::[]

== NAME

spin - A log file highlighter

== SYNOPSIS

*spin* [_OPTION_]... [_FILE_|_FOLDER_]...

== DESCRIPTION

tailspin is a command line tool that highlights log files.

== OPTIONS

*-f, --follow*::
Follow (tail) the contents of the file.
Always true if opening a folder or using the _--follow-command_ flag.

*-t, --tail*::
Start at the end of the file.
Always true if opening a folder.

*-p, --print*::
Print the output to stdout instead of viewing the contents in the pager _less_.
Always true if using stdin.

*-c, --config-path* _CONFIG_PATH_::
Specify the path to a custom configuration file.
Defaults to _XDG_CONFIG_HOME/tailspin/config.toml_ or _~/.config/tailspin/config.toml_ if not set.

*-l, --follow-command* _COMMAND_::
Continuously listen to stdout of the provided command.
The command traps the interrupt signal to allow for cancelling and resuming follow mode while inside _less_.

*--create-default-config*::
Generate a new configuration file.
Uses _XDG_CONFIG_HOME/tailspin/config.toml_ as the location if set.
Otherwise, uses _~/.config/tailspin/config.toml_ as the default path.
Will not overwrite current config file if one is already present.

*--show-default-config*::
Print the default configuration.

== SEE ALSO

*less*(1), *tail*(1)

== About

Ben Sadeh (github.com/bensadeh/tailspin)

Released under the MIT License
