= tspin(1)
:doctype: manpage
:manmanual: tailspin
:man source: tailspin {release-version}
:revdate: {docdate}

ifdef::env-github[]
:toc:
:toc-title:
:toc-placement!:
:numbered:
endif::[]

== NAME

tspin - A log file highlighter

== SYNOPSIS

*tspin* [_OPTION_]... [_FILE_|_FOLDER_]...

== DESCRIPTION

tailspin is a command line tool that highlights log files.

== OPTIONS

*-f, --follow*::
Follow (tail) the contents of the file.
Always true if opening a folder or using the _--follow-command_ flag.

*-t, --tail*::
Start at the end of the file.
Always true if opening a folder.

*-p, --print*::
Print the output to stdout instead of viewing the contents in the pager _less_.
Always true if using stdin.

*-c, --config-path* _CONFIG_PATH_::
Specify the path to a custom configuration file.
Defaults to _XDG_CONFIG_HOME/tailspin/config.toml_ or _~/.config/tailspin/config.toml_ if not set.

*-l, --follow-command* _COMMAND_::
Continuously listen to stdout of the provided command.
The command traps the interrupt signal to allow for cancelling and resuming follow mode while inside _less_.

*--words-red*::
Highlight the provided comma separated words in red

*--words-green*::
Highlight the provided comma separated words in green

*--words-yellow*::
Highlight the provided comma separated words in yellow

*--words-blue*::
Highlight the provided comma separated words in blue

*--words-magenta*::
Highlight the provided comma separated words in magenta

*--words-cyan*::
* Highlight the provided comma separated words in cyan

*--disable-builtin-keywords*::
Disables the highlighting of all builtin keyword groups (booleans, severity and REST).

*--disable-booleans*::
Disables the highlighting of booleans and nulls.

*--disable-severity*::
Disables the highlighting of severity levels.

*--disable-rest*::
Disables the highlighting of REST verbs.

== SEE ALSO

*less*(1), *tail*(1)

== About

Ben Sadeh (github.com/bensadeh/tailspin)

Released under the MIT License
