= tspin(1)
:doctype: manpage
:manmanual: tailspin
:man source: tailspin {release-version}
:revdate: {docdate}

ifdef::env-github[]
:toc:
:toc-title:
:toc-placement!:
:numbered:
endif::[]

== NAME

tspin - A log file highlighter

== SYNOPSIS

*tspin* [_OPTION_]... [_FILE_]...

== DESCRIPTION

tailspin is a command line tool that highlights log files.

== OPTIONS

_-f, --follow_::
Follow (tail) the contents of the file.
Always true when using the _--follow-command_ flag.

_-p, --print_::
Print the output to stdout instead of viewing the contents in the pager _less_.
Always true if using stdin.

_--config-path_ *CONFIG_PATH*::
Specify the path to a custom configuration file.
Defaults to *XDG_CONFIG_HOME/tailspin/theme.toml* or *~/.config/tailspin/theme.toml* if not set.

_-c, --listen-command_ *COMMAND*::
Continuously listen to the stdout of the provided command.
The command traps the interrupt signal to allow for cancelling and resuming follow mode while inside _less_.

+
.Example:
----
tspin --listen-command 'kubectl logs -f pod_name'
----

_--highlight_ *COLOR1*:__word1,word2,...__ *COLOR2*:__word3,word4,...__::
Highlight the provided comma-separated words in the specified color.
Possible colors are red, green, yellow, blue, magenta, and cyan.

+
.Example:
----
tspin logfile.txt --highlight red:error,fail --highlight green:success,ok
----

_--enable=[HIGHLIGHT_GROUP]_::
Disable all highlighting groups except the ones specified.
Comma separated list of groups.
Cannot be used with *--disable=[HIGHLIGHT_GROUP]*.

_--disable=[HIGHLIGHT_GROUP]_::
Disable the specified highlighting groups.
Comma separated list of groups.
Cannot be used with *--enable=[HIGHLIGHT_GROUP]*.

_--disable-builtin-keywords_::
Disables the highlighting of all builtin keyword groups (booleans, severity and REST).

== ENVIRONMENT VARIABLES

*TAILSPIN_PAGER*::
Set the _TAILSPIN_PAGER_ environment variable to override the default pager.
The command must include the string _[FILE]_ which will be replaced with the file path internally.
For example, _"ov -f [FILE]"_.

== SEE ALSO

*less*(1), *tail*(1)

== About

Ben Sadeh (github.com/bensadeh/tailspin)

Released under the MIT License
