[groups.date]
date = { fg = "magenta" }
time = { fg = "blue" }
zone = { fg = "red" }

[groups.number]
style = { fg = "cyan" }

[groups.quotes]
style = { fg = "yellow" }
token = '"'

[groups.ip]
segment = { fg = "blue", italic = true }
separator = { fg = "red" }

[groups.path]
segment = { fg = "green", italic = true }
separator = { fg = "yellow" }

[groups.key_value]
key = { faint = true }
separator = { fg = "white" }

[groups.process]
name = { fg = "green" }
separator = { fg = "red" }
id = { fg = "yellow" }

[groups.url]
http = { faint = true }
https = { bold = true }
host = { fg = "blue", faint = true }
path = { fg = "blue" }
query_params_key = { fg = "magenta" }
query_params_value = { fg = "cyan" }
symbols = { fg = "red" }

[[groups.keywords]]
words = ['ERROR']
style = { fg = "red" }

[[groups.keywords]]
words = ['WARN']
style = { fg = "yellow" }

[[groups.keywords]]
words = ['INFO']
style = { fg = "white" }

[[groups.keywords]]
words = ['DEBUG']
style = { fg = "green" }

[[groups.keywords]]
words = ['TRACE']
style = { faint = true }

[[groups.keywords]]
words = ['null', 'true', 'false']
style = { fg = "red", italic = true }

[[groups.keywords]]
words = ['GET']
style = { fg = "black", bg = "green" }
border = true

[[groups.keywords]]
words = ['POST']
style = { fg = "black", bg = "yellow" }
border = true

[[groups.keywords]]
words = ['PUT', 'PATCH']
style = { fg = "black", bg = "magenta" }
border = true

[[groups.keywords]]
words = ['DELETE']
style = { fg = "black", bg = "red" }
border = true